version: "3.3"
services:

  wms-database:
    container_name: wms-database
    image: store/oracle/database-enterprise:12.2.0.1-slim
    networks: 
      - inner-net
    ports:
      - 1522:1521

  wms-backend:
    container_name: wms-backend
    build:
      context: ./backend-java
    depends_on:
      - wms-database
    image: wms-backend
    networks:
      - inner-net
    environment:    
      SPRING_PROFILES_ACTIVE: oracle
      SPRING_DATASOURCE_URL: jdbc:oracle:thin:@wms-database:1521:ORCLCDB
      SPRING_DATASOURCE_USERNAME: system
      SPRING_DATASOURCE_PASSWORD: Oradoc_db1

  wms-frontend:
    container_name: wms-frontend
    image: wms-frontend
    build:
      context: ./angular-gui
    networks: 
      - inner-net

  wms-proxy:
    container_name: wms-proxy
    image: nginx:latest
    depends_on:
      - wms-backend
      - wms-frontend
    networks:
      - inner-net
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      # - ./nginx/error.log:/etc/nginx/error_log.log
      # - ./nginx/cache/:/etc/nginx/cache
      # - /etc/letsencrypt/:/etc/letsencrypt/

networks:
  inner-net:
