spring:
  data:
    rest:
      base-path: '/api'
      detection-strategy: annotated
  servlet:
    multipart:
      maxFileSize: '100MB'
      max-request-size: '110MB'
  h2:
    console:
      enabled: false
  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: update